### ISSUE TITLE
Error in snpcells[i] <- chrpos.cell(snp.info$chr[i], snp.info$pos[i],  :    replacement has length zero

### ISSUE THREAD

**Issue by Vgene2** [cgrace1978/manhplot#10]
Dear Chris,

I have the same issue that has been previously reported. I include all chromosomes (1:22) in the snpfile and infile and the configfile you provide. 
This is an extract of my input files. The complete files have both the same number of rows expanding across all chromosomes.
[infile2.txt](https://github.com/cgrace1978/manhplot/files/6912603/infile2.txt)
[snpfile2.txt](https://github.com/cgrace1978/manhplot/files/6912604/snpfile2.txt)

My command is shown below. Could you please check?
infile<-system.file("extdata","infile2.txt",package = "manhplot")
configfile<-system.file("extdata","config.txt", package = "manhplot")
snpfile<-system.file("extdata","snpfile2.txt", package = "manhplot")
manhplusplot(infile = infile,outfile = "test1", configfile = configfile, snpfile = snpfile)

Thank you.

**Comment by cgrace1978** [comment]
Check the strings in the variables infile and snpfile, I suspect they might be empty. You need to put the location of those files in those strings - you are currently looking in the installed files within the package.

Thanks,

Chris

**Comment by Vgene2** [comment]
Dear Chris,

Thank you for your quick response. I have placed my snpfile and infile in a different folder and I have checked the corresponding strings, which correspond to the correct folder.
```
> infile
[1] "C:/Users/gf/Documents/Mypipeline/infile2.txt"
> snpfile
[1] "C:/Users/gf/Documents/Mypipeline/snpfile2.txt"
> configfile
[1] "C:/Users/gf/Documents/Mypipeline/config.txt"

```
Unfortunately, I still get the same error. 
The first lines of my infile.txt are:
```
chr	pos	pvalue	maf	conseq
1	796338	0.9293146	0	0
1	833843	0.7500065	0	0
1	920719	0.9719118	0	0
1	921096	0.9772066	0	0
1	936972	0.3901463	0	0
1	993036	0.9270931	0	0
1	994185	0.9908815	0	0
1	1000018	0.7027007	0	0
1	1098863	0.7314971	0	0

```
The first lines of my snpfile.txt are:
```
markername	gene	chr	pos	eaf	OR	Pvalue	novel
1:796338:T:C	ENSG00000225880	1	796338	0.12095	0.00579006	0.9293146	FALSE
1:833843:C:G	ENSG00000228794	1	833843	0.12875	0.0391497	0.7500065	FALSE
1:920719:T:G	ENSG00000187583	1	920719	0.3914	-0.00666613	0.9719118	FALSE
1:921096:A:G	ENSG00000187961	1	921096	0.34795	-0.00421847	0.9772066	FALSE
1:936972:G:C	ENSG00000188976	1	936972	0.26915	-0.0584647	0.3901463	FALSE
1:993036:G:A	ENSG00000217801	1	993036	0.2293	-0.00187465	0.9270931	FALSE
1:994185:G:T	ENSG00000188290	1	994185	0.1502	-0.000411934	0.9908815	FALSE
1:1000018:G:A	ENSG00000187608	1	1000018	0.0358	0.0254528	0.7027007	FALSE
1:1098863:C:T	ENSG00000131591	1	1098863	0.13685	0.0263112	0.7314971	TRUE
```

**Comment by Vgene2** [comment]
I fixed the issue. Thank you for your help.
