### ISSUE TITLE
manhplot didn't display 

### ISSUE THREAD

**Issue by chenwenyan2015** [cgrace1978/manhplot#4]
Hi, Christopher
I run the Sample code `install.packages("devtools")`
`library(devtools)`
`install_github("cgrace1978/manhplot", dependencies = T, force = T)`
`library(manhplot)`
`infile<-system.file("extdata","cad.add.160614_manhformat.txt.gz",package = "manhplot")`
`configfile<-system.file("extdata","config.txt", package = "manhplot")`
`snpfile<-system.file("extdata","56cad.add.160614.variants.txt", package = "manhplot")`
`manhplusplot(infile = infile,outfile = "test", configfile = configfile, snpfile = snpfile)`
And it seems to be working fine without reporting errors , but it didn't display manhplot. 
I use it in linux and windows, they have the same problem.
linux version: R version 3.6.1 , x86_64-conda_cos6-linux-gnu (64-bit)
windowns version: R version 3.6.1, win10
Have any suggestions? Thanks
![微信图片_20191201135641](https://user-images.githubusercontent.com/31087691/69910218-6d28aa00-1442-11ea-9611-fe0567f45b03.png)

**Comment by cgrace1978** [comment]
The manhplusplot function by default generates a pdf file (A4 size), in your case a file named test.pdf should be generated, this should be generated in your default directory, to specify it to be generated in a specific directory use a full path.

Thanks,

Chris

**Comment by chenwenyan2015** [comment]
Great, good jobs. Thanks for your reply.
