### ISSUE TITLE
showgenes=TRUE gives error

### ISSUE THREAD

**Issue by PDRohde** [cgrace1978/manhplot#5]
Hi,

I am having some problems getting genes name shown on the left-hand side of the plot with showgenes=TRUE (I get a plot when showgenes=FALSE).

```
Rebuilding matrix
Reading the GWAS results...
Processing chromosome 3
Melting matrix...
Error in `$<-.data.frame`(`*tmp*`, "pvalidx", value = 160.5) : 
  replacement has 1 row, data has 0
```
Because I could not get it to work I tried with your sample data - here it works; unless I only plot chromosome 1.  If my snpfile looks like:
```
markername	NearestGene	chr	pos	eaf	OR	Pvalue	novel
rs11206510	PCSK9	1	55496039	0.847627	1.08	2.34E-08	TRUE
rs9970807	PPAP2B	1	56965664	0.915097	1.13	5E-14	TRUE
rs7528419	SORT1	1	109817192	0.78582	1.12	1.97E-23	TRUE
```
 then I get this error:
```
Rebuilding matrix
Reading the GWAS results...
Processing chromosome 1
Melting matrix...
Error in manhplusplot(infile = infile, outfile = "test", configfile = configfile,  : 
  object 'final.repel.plot' not found
```

Do you have any idea of a solution?

Cheers
Palle

**Comment by cgrace1978** [comment]
Dear Palle,
Thanks for your email. I've fixed the issues arising from using my sample data - These have been submitted to the master branch of this repository. try using this latest update with your code and let me know if there is still an issue.

Thanks,

Chris Grace

**Comment by PDRohde** [comment]
Thanks for snappy reply - but I cannot get it to work. 
Can I get you to try it out with these small examples from my own data?
I use the regular config.txt file.

[testData_snpfile.txt](https://github.com/cgrace1978/manhplot/files/4118827/testData_snpfile.txt)
[testData.txt](https://github.com/cgrace1978/manhplot/files/4118828/testData.txt)

Cheers
Palle

**Comment by cgrace1978** [comment]
OK will take a look at this data.

Thanks Chris

**Comment by cgrace1978** [comment]
Hi,

I've tested your data and was able to replicate the error. I have submitted the fix to the master branch - let me know whether this works.

Also: The snpfile you provided me with had the incorrect column name for the gene - it should be **gene** not **NearestGene**

Thanks,

Chris

**Comment by PDRohde** [comment]
Yes it works! Thanks a lot Chris!
Cheers
Palle
