### ISSUE TITLE
log scale adjustment?

### ISSUE THREAD

**Issue by sofiiako** [cgrace1978/manhplot#7]
Hi! 
Is it in any way possible to change the default log scale so that the maximum value on it is not 20 but, for example, 10? our -log10(p)'s are all lower than 10 so with the default scale it does not look nice. We would really love to use your tool for visualization in our paper but this issue is a dealbreaker(
Would b awesome if you could help! Thanks!

**Comment by cgrace1978** [comment]
Please use the argument **max.pval** in the **manhplusplot()** function to set the maximum -log10 p-value to display. 
Thanks Chris

**Comment by sofiiako** [comment]
Thank you!
