### ISSUE TITLE
replacement has length zero

### ISSUE THREAD

**Issue by dsbioanal** [cgrace1978/manhplot#8]
Hi, could you please help identify what this error means? 

```
Rebuilding matrix
Reading the GWAS results...
Error in snpcells[i] <- chrpos.cell(snp.info$chr[i], snp.info$pos[i],  : 
  replacement has length zero
```

My input file looks like this:

```
chr	pos	pvalue	maf	conseq
2	46772190	3.05e-10	0.067568	0
3	110399406	6.37e-09	0.125	0

```

```
markername	gene	chr	pos	eaf	OR	Pvalue	novel
rs150821804	MT-ND6	2	46772190	0.067568	1.96918548921183	3.05e-10	FALSE
rs73219717	MT-ND6	3	110399406	0.125	1.44044198424942	6.37e-09	FALSE

```

Could be that I am missing a small detail here, I would appreciate your feedback!

**Comment by cgrace1978** [comment]
Does you input files only contain two rows?

Thanks,

Chris Grace

**Comment by dsbioanal** [comment]
No, I have in total 221 rows but I split the chromosomes in case it doesn't handle it, for example in this run I had only chromosomes 1,2,3,4

**Comment by cgrace1978** [comment]
You need to include all the chromosomes: do you have all 22 chromosomes?

**Comment by dsbioanal** [comment]
I have sorted it out, thank you so much for this amazing package and the prompt reply! 👍
