### ISSUE TITLE
pch or geom_point() 

### ISSUE THREAD

**Issue by DM087** [cgrace1978/manhplot#9]
Hi Chris,

Thanks very much for this wonderful package. 

How can I increase the size of the dots representing each SNP on the plot? Also, is there a way to supply `pch` or `geom_point()` function in the code so that each SNP is represented by a circle (say `pch=19`) rather than the dashed lines.  

Thank you for your help.
DM

**Comment by cgrace1978** [comment]
Each individual dot represents a region containing one or more variants rather than a individual SNP.

Please read the following page in the wiki: 
https://github.com/cgrace1978/manhplot/wiki/Configuration

Let me know if you have any questions.

**Comment by DM087** [comment]
Hi Chris,

Thank you very much for that. I think I want to increase the size of the dots then. Any hint on how can I achieve that?

Thanks for your time.

**Comment by cgrace1978** [comment]
You can change the size of cells by modifying the pos.split and pval.split argument to the manhplusplot function. (pos.split default is 3MB and p-value split is -log10 of 0.125). (Before you do this read the wiki page to make sure you understand how this works).

Try increasing the size of these arguments this should increase the size of the cells.

Let me know if you have any questions

**Comment by DM087** [comment]
Thank you, Chris!
